/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/sanity/extract.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ObjectImage = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "image.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
};

export type BlogListingPage = {
  _id: string;
  _type: "blogListingPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: Seo;
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  keywords?: Array<string>;
};

export type StudentReviewsPage = {
  _id: string;
  _type: "studentReviewsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: Seo;
};

export type EligibilityAndDocumentPage = {
  _id: string;
  _type: "eligibilityAndDocumentPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: Seo;
};

export type ContactUsPage = {
  _id: string;
  _type: "contactUsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: Seo;
};

export type ApplyOnlinePage = {
  _id: string;
  _type: "applyOnlinePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: Seo;
};

export type AdmissionProcessPage = {
  _id: string;
  _type: "admissionProcessPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: Seo;
};

export type BlogPost = {
  _id: string;
  _type: "blogPost";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  featuredImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  publishedAt?: string;
  status?: "draft" | "published";
  seo?: Seo;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type Gallery = {
  _id: string;
  _type: "gallery";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  videos?: Array<{
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
    _key: string;
  }>;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  photosPageSeo?: Seo;
  videosPageSeo?: Seo;
};

export type Prospectus = {
  _id: string;
  _type: "prospectus";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  prospectus?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
};

export type MbbsInCountry = {
  _id: string;
  _type: "mbbsInCountry";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  slug?: Slug;
  heading?: string;
  bg_image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  hero?: {
    logo_image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    content?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
  };
  sections?: Array<
    | {
        type?: string;
        heading?: string;
        description?: string;
        data?: {
          headers?: Array<string>;
          rows?: Array<{
            columns?: Array<string>;
            _key: string;
          }>;
        };
        _type: "tableSection";
        _key: string;
      }
    | {
        type?: string;
        heading?: string;
        description?: string;
        content?: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?:
            | "normal"
            | "h1"
            | "h2"
            | "h3"
            | "h4"
            | "h5"
            | "h6"
            | "blockquote";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }>;
        _type: "contentSection";
        _key: string;
      }
    | {
        type?: string;
        heading?: string;
        description?: string;
        label_value?: Array<{
          label?: string;
          value?: string;
          _key: string;
        }>;
        _type: "labelValueSection";
        _key: string;
      }
  >;
  seo?: Seo;
};

export type Achievement = Array<{
  icon?: string;
  title?: string;
  subTitle?: string;
  _key: string;
}>;

export type Homepage = {
  _id: string;
  _type: "homepage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: Hero;
  hero2?: Hero2;
  countrySection?: {
    heading?: string;
    countries?: Array<{
      country?: string;
      image?: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      };
      _key: string;
    }>;
    _type: "country";
  };
  whatWeOffer?: WhatWeOffer;
  whatStudentsSay?: WhatStudentsSay;
  seo?: Seo;
};

export type WhatStudentsSay = {
  _type: "whatStudentsSay";
  heading?: string;
  content?: string;
  testimonials?: Array<
    {
      _key: string;
    } & Testimonial
  >;
};

export type WhatWeOffer = {
  _type: "whatWeOffer";
  heading?: string;
  subheading?: string;
  content?: string;
  services?: Array<
    {
      _key: string;
    } & Service
  >;
};

export type Hero2 = {
  _type: "hero2";
  heading?: string;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Hero = {
  _type: "hero";
  bgImage?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  heading?: string;
  subheading?: string;
  cta?: CtaContainer;
  achievements?: Achievement;
};

export type CtaContainer = {
  _type: "ctaContainer";
  primary?: PrimaryCTA;
  secondary?: SecondaryCTA;
};

export type Testimonial = {
  _type: "testimonial";
  name?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  university?: string;
  content?: string;
};

export type Service = {
  _type: "service";
  title?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Country = {
  _id: string;
  _type: "country";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heading?: string;
  countries?: Array<{
    country?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    _key: string;
  }>;
};

export type SecondaryCTA = {
  _type: "secondaryCTA";
  label?: string;
  href?: string;
};

export type PrimaryCTA = {
  _type: "primaryCTA";
  label?: string;
  href?: string;
};

export type Navbar = {
  _id: string;
  _type: "navbar";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  navItems?: Array<{
    name?: string;
    href?: string;
    items?: Array<{
      name?: string;
      href?: string;
      description?: string;
      _key: string;
    }>;
    _key: string;
  }>;
};

export type MbbsFaqs = {
  _id: string;
  _type: "mbbsFaqs";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heading?: string;
  items?: Array<{
    question?: string;
    answer?: string;
    _key: string;
  }>;
  seo?: Seo;
};

export type WhyStudyMBBSAbroad = {
  _id: string;
  _type: "whyStudyMBBSAbroad";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heading?: string;
  items?: Array<{
    icon?: string;
    title?: string;
    _key: string;
  }>;
  seo?: Seo;
};

export type DirectorsMessage = {
  _id: string;
  _type: "directorsMessage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heading?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  seo?: Seo;
};

export type Services = {
  _id: string;
  _type: "services";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heading?: string;
  description?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  servicesItems?: Array<{
    icon?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    title?: string;
    _key: string;
  }>;
  seo?: Seo;
};

export type AboutUs = {
  _id: string;
  _type: "aboutUs";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  intro?: Intro;
  achievements?: Achievements;
  ourTeam?: OurTeam;
  seo?: Seo;
};

export type OurTeam = {
  _type: "ourTeam";
  heading?: string;
  subHeading?: string;
  teamMembers?: Array<{
    image?: ObjectImage;
    name?: string;
    designation?: string;
    _key: string;
  }>;
};

export type Achievements = {
  _type: "achievements";
  title?: string;
  achievementItems?: Array<{
    icon?: string;
    title?: string;
    _key: string;
  }>;
};

export type Intro = {
  _type: "intro";
  heading?: string;
  subheading?: string;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  introImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | ObjectImage
  | BlogListingPage
  | Seo
  | StudentReviewsPage
  | EligibilityAndDocumentPage
  | ContactUsPage
  | ApplyOnlinePage
  | AdmissionProcessPage
  | BlogPost
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | SanityFileAssetReference
  | Gallery
  | Prospectus
  | MbbsInCountry
  | Achievement
  | Homepage
  | WhatStudentsSay
  | WhatWeOffer
  | Hero2
  | Hero
  | CtaContainer
  | Testimonial
  | Service
  | Country
  | SecondaryCTA
  | PrimaryCTA
  | Navbar
  | MbbsFaqs
  | WhyStudyMBBSAbroad
  | DirectorsMessage
  | Services
  | AboutUs
  | OurTeam
  | Achievements
  | Intro
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/queries/blog.ts
// Variable: BLOG_POSTS_QUERY
// Query: *[_type == "blogPost" && status == "published"] | order(publishedAt desc) [$start...$end] {    _id,    title,    slug,    excerpt,    publishedAt,    featuredImage {      ...,      asset-> {        _id,        url,        metadata {          dimensions,          lqip        }      }    }  }
export type BLOG_POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  excerpt: string | null;
  publishedAt: string | null;
  featuredImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        dimensions: SanityImageDimensions | null;
        lqip: string | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
}>;

// Source: src/sanity/queries/blog.ts
// Variable: BLOG_POST_BY_SLUG_QUERY
// Query: *[_type == "blogPost" && slug.current == $slug][0] {    _id,    title,    slug,    excerpt,    content,    publishedAt,    featuredImage {      ...,      asset-> {        _id,        url,        metadata {          dimensions,          lqip        }      }    },    seo  }
export type BLOG_POST_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  excerpt: string | null;
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  publishedAt: string | null;
  featuredImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        dimensions: SanityImageDimensions | null;
        lqip: string | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  seo: Seo | null;
} | null;

// Source: src/sanity/queries/blog.ts
// Variable: BLOG_POSTS_COUNT_QUERY
// Query: count(*[_type == "blogPost" && status == "published"])
export type BLOG_POSTS_COUNT_QUERY_RESULT = number;

// Source: src/sanity/queries/blog.ts
// Variable: BLOG_POSTS_SLUGS_QUERY
// Query: *[_type == "blogPost" && status == "published"].slug.current
export type BLOG_POSTS_SLUGS_QUERY_RESULT = Array<string | null>;

// Source: src/sanity/queries/blog.ts
// Variable: RECENT_BLOG_POSTS_QUERY
// Query: *[_type == "blogPost" && status == "published"] | order(publishedAt desc)[0...3] {    _id,    title,    slug,    excerpt,    publishedAt,    status,    featuredImage {      ...,      asset-> {        _id,        url,        metadata {          dimensions,          lqip        }      }    }  }
export type RECENT_BLOG_POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  excerpt: string | null;
  publishedAt: string | null;
  status: "published";
  featuredImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        dimensions: SanityImageDimensions | null;
        lqip: string | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "blogPost" && status == "published"] | order(publishedAt desc) [$start...$end] {\n    _id,\n    title,\n    slug,\n    excerpt,\n    publishedAt,\n    featuredImage {\n      ...,\n      asset-> {\n        _id,\n        url,\n        metadata {\n          dimensions,\n          lqip\n        }\n      }\n    }\n  }\n': BLOG_POSTS_QUERY_RESULT;
    '\n  *[_type == "blogPost" && slug.current == $slug][0] {\n    _id,\n    title,\n    slug,\n    excerpt,\n    content,\n    publishedAt,\n    featuredImage {\n      ...,\n      asset-> {\n        _id,\n        url,\n        metadata {\n          dimensions,\n          lqip\n        }\n      }\n    },\n    seo\n  }\n': BLOG_POST_BY_SLUG_QUERY_RESULT;
    '\n  count(*[_type == "blogPost" && status == "published"])\n': BLOG_POSTS_COUNT_QUERY_RESULT;
    '\n  *[_type == "blogPost" && status == "published"].slug.current\n': BLOG_POSTS_SLUGS_QUERY_RESULT;
    '\n  *[_type == "blogPost" && status == "published"] | order(publishedAt desc)[0...3] {\n    _id,\n    title,\n    slug,\n    excerpt,\n    publishedAt,\n    status,\n    featuredImage {\n      ...,\n      asset-> {\n        _id,\n        url,\n        metadata {\n          dimensions,\n          lqip\n        }\n      }\n    }\n  }\n': RECENT_BLOG_POSTS_QUERY_RESULT;
  }
}
