/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    navbar: Navbar;
  };
  globalsSelect: {
    navbar: NavbarSelect<false> | NavbarSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  pageType: 'home' | 'about' | 'services' | 'directorsMessage' | 'whyStudyMBBSAbroad' | 'mbbsFaqs';
  homePageContent?: {
    hero: {
      heading: string;
      subheading: string;
      cta: {
        primary: {
          label: string;
          href: string;
        };
        secondary: {
          label: string;
          href: string;
        };
        href: string;
      };
      hero_2: {
        heading: string;
        content: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        image: string | Media;
      };
      countries: {
        country: string;
        image: string | Media;
        id?: string | null;
      }[];
      what_we_offer: {
        heading: string;
        subheading: string;
        content: string;
        services?:
          | {
              title: string;
              image: string | Media;
              id?: string | null;
            }[]
          | null;
        what_students_say: {
          heading: string;
          content: string;
          testimonials?:
            | {
                name: string;
                image: string | Media;
                university: string;
                content: string;
                id?: string | null;
              }[]
            | null;
        };
      };
    };
  };
  aboutPageContent?: {
    intro?: {
      heading?: string | null;
      subheading?: string | null;
      content?: {
        root: {
          type: string;
          children: {
            type: string;
            version: number;
            [k: string]: unknown;
          }[];
          direction: ('ltr' | 'rtl') | null;
          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
          indent: number;
          version: number;
        };
        [k: string]: unknown;
      } | null;
    };
    achievements?: {
      title?: string | null;
      achivementItems?:
        | {
            icon?: string | null;
            title?: string | null;
            id?: string | null;
          }[]
        | null;
    };
    ourTeam?: {
      title?: string | null;
      description?: string | null;
      teamMembers?:
        | {
            image: string | Media;
            name: string;
            designation: string;
            id?: string | null;
          }[]
        | null;
    };
  };
  servicePageContent?: {
    serviceIntro?: {
      heading?: string | null;
      description?: {
        root: {
          type: string;
          children: {
            type: string;
            version: number;
            [k: string]: unknown;
          }[];
          direction: ('ltr' | 'rtl') | null;
          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
          indent: number;
          version: number;
        };
        [k: string]: unknown;
      } | null;
      serviceList?:
        | {
            title?: string | null;
            icon?: string | null;
            id?: string | null;
          }[]
        | null;
    };
  };
  directorsMessageContent?: {
    directorsMessage?: {
      heading?: string | null;
      content?: {
        root: {
          type: string;
          children: {
            type: string;
            version: number;
            [k: string]: unknown;
          }[];
          direction: ('ltr' | 'rtl') | null;
          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
          indent: number;
          version: number;
        };
        [k: string]: unknown;
      } | null;
    };
  };
  whyStudyMBBSAbroadContent?: {
    whyStudyMBBSAbroad?: {
      heading?: string | null;
      listItems?:
        | {
            title?: string | null;
            icon?: string | null;
            id?: string | null;
          }[]
        | null;
    };
  };
  mbbsFaqsContent?: {
    mbbsFaqs?: {
      heading?: string | null;
      listItems?:
        | {
            question?: string | null;
            answer?: string | null;
            id?: string | null;
          }[]
        | null;
    };
  };
  mbbsInCountryContent?: {
    mbbsInCountry: {
      slug: string;
      heading: string;
      bg_image: string | Media;
      hero: {
        logo_image: string | Media;
        content: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
      };
      universities: {
        title: string;
        table?:
          | {
              name: string;
              year: string;
              location: string;
              fees: string;
              id?: string | null;
            }[]
          | null;
      };
      about: {
        title: string;
        content: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        facts?:
          | {
              title: string;
              icon: string;
              value: string;
              id?: string | null;
            }[]
          | null;
      };
      eligibility: {
        title: string;
        content: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
      };
      why_choose: {
        title: string;
        content: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
      };
      city_attractions: {
        title: string;
        image: string | Media;
      };
    };
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  pageType?: T;
  homePageContent?:
    | T
    | {
        hero?:
          | T
          | {
              heading?: T;
              subheading?: T;
              cta?:
                | T
                | {
                    primary?:
                      | T
                      | {
                          label?: T;
                          href?: T;
                        };
                    secondary?:
                      | T
                      | {
                          label?: T;
                          href?: T;
                        };
                    href?: T;
                  };
              hero_2?:
                | T
                | {
                    heading?: T;
                    content?: T;
                    image?: T;
                  };
              countries?:
                | T
                | {
                    country?: T;
                    image?: T;
                    id?: T;
                  };
              what_we_offer?:
                | T
                | {
                    heading?: T;
                    subheading?: T;
                    content?: T;
                    services?:
                      | T
                      | {
                          title?: T;
                          image?: T;
                          id?: T;
                        };
                    what_students_say?:
                      | T
                      | {
                          heading?: T;
                          content?: T;
                          testimonials?:
                            | T
                            | {
                                name?: T;
                                image?: T;
                                university?: T;
                                content?: T;
                                id?: T;
                              };
                        };
                  };
            };
      };
  aboutPageContent?:
    | T
    | {
        intro?:
          | T
          | {
              heading?: T;
              subheading?: T;
              content?: T;
            };
        achievements?:
          | T
          | {
              title?: T;
              achivementItems?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    id?: T;
                  };
            };
        ourTeam?:
          | T
          | {
              title?: T;
              description?: T;
              teamMembers?:
                | T
                | {
                    image?: T;
                    name?: T;
                    designation?: T;
                    id?: T;
                  };
            };
      };
  servicePageContent?:
    | T
    | {
        serviceIntro?:
          | T
          | {
              heading?: T;
              description?: T;
              serviceList?:
                | T
                | {
                    title?: T;
                    icon?: T;
                    id?: T;
                  };
            };
      };
  directorsMessageContent?:
    | T
    | {
        directorsMessage?:
          | T
          | {
              heading?: T;
              content?: T;
            };
      };
  whyStudyMBBSAbroadContent?:
    | T
    | {
        whyStudyMBBSAbroad?:
          | T
          | {
              heading?: T;
              listItems?:
                | T
                | {
                    title?: T;
                    icon?: T;
                    id?: T;
                  };
            };
      };
  mbbsFaqsContent?:
    | T
    | {
        mbbsFaqs?:
          | T
          | {
              heading?: T;
              listItems?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
            };
      };
  mbbsInCountryContent?:
    | T
    | {
        mbbsInCountry?:
          | T
          | {
              slug?: T;
              heading?: T;
              bg_image?: T;
              hero?:
                | T
                | {
                    logo_image?: T;
                    content?: T;
                  };
              universities?:
                | T
                | {
                    title?: T;
                    table?:
                      | T
                      | {
                          name?: T;
                          year?: T;
                          location?: T;
                          fees?: T;
                          id?: T;
                        };
                  };
              about?:
                | T
                | {
                    title?: T;
                    content?: T;
                    facts?:
                      | T
                      | {
                          title?: T;
                          icon?: T;
                          value?: T;
                          id?: T;
                        };
                  };
              eligibility?:
                | T
                | {
                    title?: T;
                    content?: T;
                  };
              why_choose?:
                | T
                | {
                    title?: T;
                    content?: T;
                  };
              city_attractions?:
                | T
                | {
                    title?: T;
                    image?: T;
                  };
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navbar".
 */
export interface Navbar {
  id: string;
  logo: string | Media;
  navItems?:
    | {
        name: string;
        href?: string | null;
        items?:
          | {
              title: string;
              href: string;
              description: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navbar_select".
 */
export interface NavbarSelect<T extends boolean = true> {
  logo?: T;
  navItems?:
    | T
    | {
        name?: T;
        href?: T;
        items?:
          | T
          | {
              title?: T;
              href?: T;
              description?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}